<b>Md. Atiqur Rahman Sifat<br>ID: 0432410005101124 - 8B2

In [ ]:
myCGPA = [3.0, 3.5, 3.8, 4.0]

# sw: Semester Wise, myCGPA: Cumulative Grade Point Average
squareofmyCGPA = [sw**2 for sw in myCGPA]
print(squareofmyCGPA)

[9.0, 12.25, 14.44, 16.0]


Self Study:: Dictionary{Key: Value} & Tuple() <- Tuple cannot be changed after creation.

In [4]:
import numpy as np
zeroArray = np.zeros((3, 4), dtype=int)
print(zeroArray)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
oneArray = np.ones((2, 5), dtype=int)
print(oneArray)

[[1 1 1 1 1]
 [1 1 1 1 1]]


Self Study:: np.array(), np.dot()

In [8]:
matrixfromArray = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3)
print(matrixfromArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
customArraybyArange = np.arange(10,100,10).reshape(3, 3) # Start: 10, Stop: 100(Excluded), Step: 10
print(customArraybyArange)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
